# Usage:
#   docker-compose build
#   docker-compose run autosync

version: '3'

services:

  autosync:
    build: .

    volumes:
      # let container access host docker daemon
      - //var/run/docker.sock:/var/run/docker.sock

      # for development, mount the source code from the host
      - .:/code

      # mount host home dir for persistent storage of audio files and fingerprints
      - ~/critrolesync-data:/data

    network_mode: host
