# To run the autosync algorithm:
#   docker compose build
#   docker compose run autosync episode_ids
# where episode_ids takes a form like C1E1 or C2E1-141
#
# To host the site locally:
#   docker compose up web -d
# then visit http://localhost

version: "3"

services:


  autosync:
    build: .

    volumes:
      # let container access host docker daemon
      - //var/run/docker.sock:/var/run/docker.sock

      # for development, mount the source code from the host
      - .:/code

      # mount host home dir for persistent storage of audio files and fingerprints
      - ~/critrolesync-data:/data

    # ensure this service can talk to postgres containers spawned at runtime
    network_mode: host


  web:
    image: nginx

    volumes:
      # serve html from the docs directory
      - ./docs:/usr/share/nginx/html

    ports:
      # map port 80 to the host
      - "80:80"
