# Usage:
#   docker-compose build
#   docker-compose run autosync

version: '3'

services:

  autosync:
    build: .
    volumes:
      - .:/code
      - //var/run/docker.sock:/var/run/docker.sock  # let container access host docker daemon
    network_mode: host
